### ISSUE TITLE
第1次编译失败后，再次编译部分module不生成aar

### ISSUE THREAD

**Issue by TwilightKHQ** [trycatchx/RocketX#50]
开启加速
项目清理 RocketX缓存清理
第1次编译失败 再次编译通过 但是有的module不生成aar
运行App崩溃报错 没有找到对应的类

报错信息
```
D:\Program\Project\xxxx\android-current\qrscan\build\tmp\kapt3\classes\debug does not exist

Execution failed for task ':qrscan:extractDebugAnnotations'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > Internal error: unexpected lint return value -1
```
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "xxxx" on path: 
DexPathList[[zip file "/data/app/~~mYGoUcKafRv320Uvux1VKA==/xxxxx-Nn5s_U-ZStFns6h6I30Bew==/base.apk"]
```
环境
```
    distributionUrl=https\://services.gradle.org/distributions/gradle-7.1.1-all.zip

    classpath "com.android.tools.build:gradle:7.0.0"
    classpath "io.github.trycatchx:rocketx:1.1.0"

    RocketX {
        openLog = true
        //指定哪些模块不打成 aar ，字符串为 module.path
//        excludeModule = [":qrscan"]
    }
```

不开启加速
项目清理 RocketX缓存清理
编译没问题 运行没问题

不知道问题出在哪 帮忙看一下

**Comment by trycatchx** [comment]
@TwilightKHQ 查看一下:
1、 工程根目录/.gradle/.rocketxcache/.app/ 下的所有module  aar 是否有生成。
![image](https://user-images.githubusercontent.com/6050250/168975751-bacd8033-9231-45b6-963a-b9d176f409f8.png)
2、ClassNotFoundException 报错的类是 qrscan 模块的，还是 qrscan 依赖模块中的 class ？

**Comment by TwilightKHQ** [comment]
@trycatchx  
1. qrscan 的aar没有生成 其他的模块都有
2. 报错的类就是qrscan模块的 qrscan是一个单独的模块 没有依赖其他的模块

**Comment by trycatchx** [comment]
@TwilightKHQ   是否使用了： excludeModule = [":qrscan"]，看你的 log 有 `task ':qrscan:extractDebugAnnotations'` 理论是使用了。

目前看起来像是注解上的问题？ 检查是否有空的 Def 譬如：`@IntDef({}) `or `@StringDef({}) .`

**Comment by trycatchx** [comment]
@TwilightKHQ 请问问题有进展吗？

**Comment by TwilightKHQ** [comment]
@trycatchx 
确实是注解的问题，移除掉这个模块下面的两个非空注解之后第一次编译就能通过
但是另一个模块也有IntDef注解 没有出现问题
所以现在问题的根本原因还是没找到

**Comment by trycatchx** [comment]
@TwilightKHQ 好的，理论上只要有空的 def 都是不允许的。另一个模块为什么能编译过去，我这边没法提供帮助。

**Comment by TwilightKHQ** [comment]
我再琢磨琢磨
