### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by shenyunhuan** [trycatchx/RocketX#52]
配置文件如下
---------根build
buildscript {
    dependencies {
        classpath('com.google.dagger:hilt-android-gradle-plugin:2.42')
        classpath('io.github.trycatchx:rocketx:1.1.0')
    }
}
plugins {
    id 'com.android.application' version '7.2.0' apply false
    id 'com.android.library' version '7.2.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.6.20' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

-----------------settings
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()

    }

}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
        }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven {
            url 'https://maven.aliyun.com/nexus/content/repositories/releases/'
        }
        maven {
            url 'https://maven.aliyun.com/nexus/content/repositories/releases/'
        }
    }
}
include ':app'
---------app build
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.rocketx'
}

报错 
An exception occurred applying plugin request [id: 'com.rocketx']
> Failed to apply plugin 'com.rocketx'.
   > Build was configured to prefer settings repositories over project repositories but repository 'flatDir' was added by plugin 'com.rocketx'

**Comment by trycatchx** [comment]
@shenyunhuan  去掉 repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

**Comment by shenyunhuan** [comment]
去掉这个更加报错，之前就试过

**Comment by shenyunhuan** [comment]
所有的第三方包都找不到了

**Comment by trycatchx** [comment]
把 repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) 改成repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

@chenfei0928  问题同 [issue31](https://github.com/trycatchx/RocketXPlugin/issues/31),  [解决办法](https://github.com/trycatchx/RocketXPlugin/issues/31#issuecomment-1017411649)
[具体细节](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration)

**Comment by shenyunhuan** [comment]
1 problem was found storing the configuration cache.
- Plugin 'com.rocketx': registration of listener on 'Gradle.addBuildListener' is unsupported
  See https://docs.gradle.org/7.4.2/userguide/configuration_cache.html#config_cache:requirements:build_listeners
