### ISSUE TITLE
修改commonUI 源码依赖不生效，还是打包成aar

### ISSUE THREAD

**Issue by nxtzhengyongbo** [trycatchx/RocketX#56]
修改底层ui，添加margin不生效，在app ->build.gradle ->android 下添加   RocketX {
        openLog = true
        //指定哪些模块不打成 aar ，字符串为 module.path
        excludeModule = [':commonUI']
    }
想源码依赖，但是还是打包成aar

`

import com.xx.plugin.versioncontroller.*

apply from: 'share_config.gradle'
apply plugin: 'com.rocketx'
android {
    compileSdkVersion BuildVersionTool.COMPILE_SDK_VERSION as int
    buildToolsVersion BuildVersionTool.BUILD_TOOLS_VERSION as String
    defaultConfig {
        applicationId "com.xx.xx"
        minSdkVersion BuildVersionTool.MIN_SDK_VERSION as int
        targetSdkVersion BuildVersionTool.TARGET_SDK_VERSION as int
        versionName BuildVersionTool.VERSION_NAME as String
        versionCode BuildVersionTool.VERSION_CODE as int
        multiDexEnabled true
        aaptOptions.cruncherEnabled = false
        aaptOptions.useNewCruncher = false
        buildConfigField "boolean", "ENABLE_CAPTURE", "${project.hasProperty('enable_charles')}"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [AROUTER_MODULE_NAME: project.getName()]
            }
        }
        ndk {
            abiFilters 'armeabi', 'arm64-v8a', 'armeabi-v7a'
        }

    dataBinding {
        enabled = true
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    

    RocketX {
        openLog = true
        //指定哪些模块不打成 aar ，字符串为 module.path
        excludeModule = [':commonUI']
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api project(':apiModule')
    implementation project(':commonUI')
    
    implementation project(':userCenter')
    implementation project(':share')
    implementation project(':msgCenterModule')
    implementation project(':tideMap')

}
`

**Comment by trycatchx** [comment]
@nxtzhengyongbo 
1、看下 commonUI 是是不是一级目录
2、在根目录/.gradle/.rocketxcache/.app/ 目录下删除 对应的commonUI.aar ，然后进行编译看下是否还生成 aar 。

**Comment by nxtzhengyongbo** [comment]
> @nxtzhengyongbo 1、看下 commonUI 是是不是一级目录 2、在根目录/.gradle/.rocketxcache/.app/ 目录下删除 对应的commonUI.aar ，然后进行编译看下是否还生成 aar 。

commonUI不是一级目录，我们是每个moudle都是一个project，这个project和app的project同级
删除aar没用，还是生成commonUI.aar

**Comment by trycatchx** [comment]
@nxtzhengyongbo  如果不是一级目录，要补上它的前缀。譬如B module 的路径为： A/B ，那么它的 path 就是
excludeModule = [':A:B']

**Comment by nxtzhengyongbo** [comment]
> @nxtzhengyongbo 如果不是一级目录，要补上它的前缀。譬如B module 的路径为： A/B ，那么它的 path 就是 excludeModule = [':A:B']

我试试
