### ISSUE TITLE
请问改为发布到远端maven仓库有示例吗，需要改哪些地方呢

### ISSUE THREAD

**Issue by king-ma1993** [trycatchx/RocketX#58]
请问改为发布到远端maven仓库有示例吗，需要改哪些地方呢

**Comment by trycatchx** [comment]
[MavenPublish.kt](https://github.com/trycatchx/RocketX/blob/9979fc3aba4b63300b4ded88cc09f659fd39c41e/buildSrc/src/main/kotlin/plugin/localmaven/MavenPublish.kt#L35)

**Comment by LiamU** [comment]
@trycatchx 可否支持下配置自动发布到远程maven仓库

**Comment by trycatchx** [comment]
@LiamU  非常抱歉，目前没有这个计划呢。
