### ISSUE TITLE
demo 编译报错

### ISSUE THREAD

**Issue by haizhiyun** [trycatchx/RocketX#59]
> Task :app:compileDevelopDebugKotlin FAILED
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (7, 12): Unresolved reference: projectb
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (8, 12): Unresolved reference: projectc
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (13, 33): Unresolved reference: activity_projectc
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (15, 35): Unresolved reference: MainActivityC
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (20, 9): Unresolved reference: MainActivityB
e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (21, 9): Unresolved reference: MainActivityC
>>>>     
构建开始时间：2022-08-16 :06:49:23
构建结束时间：2022-08-16 :06:49:25
构建总耗时：1598ms=1.59s

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevelopDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s

**Comment by haizhiyun** [comment]
> > Task :app:compileDevelopDebugKotlin FAILED
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (7, 12): Unresolved reference: projectb
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (8, 12): Unresolved reference: projectc
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (13, 33): Unresolved reference: activity_projectc
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (15, 35): Unresolved reference: MainActivityC
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (20, 9): Unresolved reference: MainActivityB
> > e: /Users/user/github/RocketX/app/src/main/java/com/rocketx/MainActivityApp.kt: (21, 9): Unresolved reference: MainActivityC
> > > > >
> 
> 构建开始时间：2022-08-16 :06:49:23 构建结束时间：2022-08-16 :06:49:25 构建总耗时：1598ms=1.59s
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:compileDevelopDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 3s

编译命令 ./gradlew :app:assembleDevelopDebug ，出现新的错误：（版本1.1.1）

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeGenClassesDevelopDebug'.
> Could not resolve all files for configuration ':app:developDebugCompileClasspath'.
   > Could not find com.libbz.projectB:projectB:1.0.
     Required by:
         project :app

**Comment by trycatchx** [comment]
![image](https://user-images.githubusercontent.com/6050250/185104887-1d94e3aa-d2b5-4960-83ef-71791f6351db.png)
我在mac 上编译了下，是没有问题的。请问你有改动吗？是window 还是mac ？

**Comment by haizhiyun** [comment]
> ![image](https://user-images.githubusercontent.com/6050250/185104887-1d94e3aa-d2b5-4960-83ef-71791f6351db.png) 我在mac 上编译了下，是没有问题的。请问你有改动吗？是window 还是mac ？

mac m1 max

**Comment by haizhiyun** [comment]
好了，关闭火箭、然后清理下缓存，aar 文件，重新打开就好了，应该是某次缓存出问题
