### ISSUE TITLE
AGP 7.2.2 sync 失败

### ISSUE THREAD

**Issue by Jadyli** [trycatchx/RocketX#64]
希望能适配下

**Comment by trycatchx** [comment]
@Jadyli 可以把异常信息贴一下吗？

**Comment by Jadyli** [comment]
有很多不同的异常信息，是必现的，就没有贴

**Comment by snailflying** [comment]
反馈问题就把异常信息贴出来。你不贴人家怎么修复？你那边必现不代表其他人也必现。

**Comment by Jadyli** [comment]
> 反馈问题就把异常信息贴出来。你不贴人家怎么修复？你那边必现不代表其他人也必现。

搞不懂，你怎么知道我不是确定了环境啥的都没问题才这样评论的，正是因为确定了必现，只要作者在 demo 里把 agp 改成 7.2.2 就能出现，我才没贴的。我不贴，人家怎么就不能修复了？你自己能力不行就说作者不行？吃饱了撑的。

**Comment by Jadyli** [comment]
问题关闭，不想跟杠精继续说了。
