### ISSUE TITLE
请教一下，这部分禁用transform任务的逻辑，有没有办法在build.gradle里面写，而不是在插件里？

### ISSUE THREAD

**Issue by xingchenxuanfeng** [trycatchx/RocketX#68]
https://github.com/trycatchx/RocketX/blob/cb00d9a2c1af2b8c4043468b45b9da42f6f25e1b/buildSrc/src/main/kotlin/plugin/utils/PluginUtil.kt#L143

请教一下，这部分禁用transform任务的逻辑，有没有办法在build.gradle里面写，而不是在插件里？

**Comment by trycatchx** [comment]
@xingchenxuanfeng  

excludeTransForms： 编译阶段可以禁用的 transform ，编译速度更快（可通过build 的 log 搜索关键字 transFormList 查看自己项目引用了哪些 transform，并手动配置在 gradle.properties 文件下）
# 使用空格间隔开
excludeTransForms = com.alibaba.arouter AAA bbb

**Comment by trycatchx** [comment]
可以的。如果你需要 在build.gradle ，只需要把KTS 的语言转成 groovy 。当然如果你是用的build.gradle.kts ,可以原封不动的 copy 过去
